--- 
  files: 
    - 
      destination: /home/
      source: /
  hooks: 
    ApplicationStart: 
      - 
        location: /codedeploy/application_start.sh
    ApplicationStop: 
      - 
        location: /codedeploy/application_stop.sh
    BeforeInstall: 
      - 
        location: /codedeploy/before_install.sh
  os: linux
  version: 0.0