
files: 
    destination: /home/ubuntu/podcast/
    source: /
hooks: 
    ApplicationStart: 
    - 
        location: /codedeploy/application-start.sh
    ApplicationStop: 
    - 
        location: /codedeploy/application-stop.sh
    BeforeInstall: 
    - 
        location: /codedeploy/before-install.sh
os: linux
version: 0.0