--- 
  files: 
    - 
      destination: /home/ubuntu/podcast/server/
      source: /
  hooks: 
    ApplicationStop:
      -
        location: /scripts/applicationStop.sh
        timeout: 180
    ApplicationStart: 
      - 
        location: /scripts/applicationStart.sh
        timeout: 180
    BeforeInstall: 
      - 
        location: /scripts/beforeInstall.sh
        timeout: 180
  os: linux
  version: 0.0