--- 
  files: 
    - 
      destination: /home/ubuntu/podcast/
      source: /
  hooks: 
    ApplicationStart: 
      - 
        location: /codedeploy/start_server.sh  
    BeforeInstall: 
      - 
        location: /codedeploy/install_dependencies.sh
  os: linux
  version: 0.0